version: '3'

services:
  api:
    container_name: api
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    command: gunicorn -w 1 -b 0.0.0.0:8000 app:app --daemon
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "5000:5000"
    depends_on:
      - api